[toolchain]
anchor_version = "0.30.0"

[features]
resolution = false
skip-lint = false

[programs.devnet]
puppet = "BKxpuFwFT4UYTVegRDUc9WtkU6LXxMDJ1QCuck4FFhke"
transfer_hook_whale = "7dP5DK3KgR1rp5LjzxuZALouQzATpgbt8BwytcQhpiYN"

[programs.localnet]
puppet = "BKxpuFwFT4UYTVegRDUc9WtkU6LXxMDJ1QCuck4FFhke"
transfer_hook_whale = "7dP5DK3KgR1rp5LjzxuZALouQzATpgbt8BwytcQhpiYN"

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id_user11.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
