[toolchain]
anchor_version = "0.30.0"

[features]
resolution = false
skip-lint = false

[programs.devnet]
puppet = "BkZHVRYhg838XMX7NKCwHgsctC2ir5iqYBH2GyQwFZxT"
transfer_hook_whale = "F72oEg6rd4ncb9x1jGYDArZ5Hg9XrfwUodNmDUqRSsbi"

[programs.localnet]
puppet = "7M1JLkXJWjr6fxRDL2pSa2VWgEEEEDPYwtVRnoZZKeCr"
transfer_hook_whale = "8zFPYjKA9aUDobXpy8v4dExuXfM69PEkXuUpxQETnQq5"

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
