[toolchain]
anchor_version = "0.30.0"

[features]
resolution = false
skip-lint = false

[programs.devnet]
puppet = "2FQwuzDa6xZ6QCY3DWozMWmRVK6CPxGKKuwaGGsiVT87"
transfer_hook_whale = "Fx1kWvaPZqcp6SWVNYLZD9Z2LoQB5VebfpPu22ejvLB1"

[programs.localnet]
puppet = "2FQwuzDa6xZ6QCY3DWozMWmRVK6CPxGKKuwaGGsiVT87"
transfer_hook_whale = "Fx1kWvaPZqcp6SWVNYLZD9Z2LoQB5VebfpPu22ejvLB1"

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
